version: "3"
services:
  hub:
    image: selenium/hub

  chrome:
    image: selenium/node-chrome
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub

  search-module:
        image: rajgopalstuff/selenium-docker
        container_name: search-module
        depends_on:
          - chrome
        environment:
          - MODULE=search-module.xml
          - BROWSER=chrome
          - HUB_HOST=hub
        volumes:
          - ./output/search-result:/usr/share/udemy/test-output    